Stop failing of ipinfo.io calls.. retry again and again

diff --git a/lab1/ipsoflog b/lab1/ipsoflog
--- a/lab1/ipsoflog
+++ b/lab1/ipsoflog
@@ -16,26 +16,35 @@
 
 # Set the variables to use in the script
 LOGFILE=$1
-if [ -z "$2" ]; then
-   SEARCH=$2
-else
+if [ -z $2 ]; then
    SEARCH="Authentication failure"
+else
+   SEARCH=$2
 fi
 
 # IP address regular expression
 REGEX='[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'
 
+rm -f /tmp/top10ips
 #Get all the IPS with that search criteria
-grep $SEARCH $LOGFILE | grep -o $REGEX $LOGFILE | sort | uniq -c | sort -nr | head -10 | sort > /tmp/top10ips
+grep "$SEARCH" $LOGFILE | grep -o $REGEX | sort | uniq -c | sort -nr | head -10 > /tmp/top10ips
+
+#Make some tmp folders and make sure they are empty
+mkdir -p /tmp/ipswithloc;
+rm /tmp/ipswithloc/*;
+mkdir -p /tmp/finalips;
+rm /tmp/finalips/*;
 
 #PARSE TOP 10 IPS From File and find their locations
-mkdir -p /tmp/ipswithloc
 awk '{print $1, $2}' /tmp/top10ips | while read o i; do
-rm -f /tmp/ipswithloc/$i.txt;
-sleep .25; #Don't make too many requests, too quickly
-wget -O /tmp/ipswithloc/$i.txt -t 1 http://ipinfo.io/$i 2> /dev/null;
-mkdir -p /tmp/finalips;
-rm -f /tmp/finalips/$i.txt;
+
+#I was running into issues where ipinfo would send an error. Gotta retry 
+while [ 1 ]; do
+    wget -q -w 5 --random-wait -O /tmp/ipswithloc/$i.txt http://www.ipinfo.io/$i --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 --continue
+    if [ $? = 0 ]; then break; fi; # check return value, break if successful (0)
+    sleep 1s;
+done;
+
 echo -n $o >> /tmp/finalips/$i.txt;
 echo -n " " >> /tmp/finalips/$i.txt;
 echo -n $i >> /tmp/finalips/$i.txt;
